### ISSUE TITLE
[Provider]: Split JavaScript

### ISSUE THREAD

**Issue by patricioe** [open-feature/docs.openfeature.dev#116]
### SDK

JavaScript/TypeScript

### Vendor/Tool

Split

### Maintainer

Vendor

### Artifacts

npm:  https://www.npmjs.com/package/@splitsoftware/openfeature-nodejs-split-provider

### Repository

https://github.com/splitio/split-openfeature-provider-nodejs

### Anything else?

static/img/split-no-fill.svg

**Comment by beeme1mr** [comment]
Looks good, thanks!
