### ISSUE TITLE
Search Support

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/docs.openfeature.dev#12]
Add search support to the docs. Docusaurus has Algolia support out of the box. That should work well for our use case.

https://docusaurus.io/docs/search

**Comment by beeme1mr** [comment]
We can request an open-source license for Algolia as soon as we have the core documentation in place.

**Comment by toddbaert** [comment]
I think @AnaisUrlichs had some ideas for search. Would like her input here.

**Comment by beeme1mr** [comment]
I've added `@cmfcmf/docusaurus-search-local` for now. It's basic but was easy to setup.

**Comment by beeme1mr** [comment]
Local search is working fine for now.
