### ISSUE TITLE
[FEATURE] drop me into the docs

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/docs.openfeature.dev#124]
### Requirements

I think the content on this page: https://docs.openfeature.dev/

should actually just get put on openfeature.dev directly.

Going to docs.openfeature.dev should drop us into https://docs.openfeature.dev/docs/reference/intro

Or maybe the main page there should have a clearer "here are the 4 docs areas. pick one" CTA rather than showing the code.

**Comment by beeme1mr** [comment]
What do you think about just moving the docs to openfeature.dev? We could setup a redirect for anyone trying to hit docs.openfeature.dev directly.

**Comment by justinabrahms** [comment]
I buy that. If we do that, the docs url should redirect to the docs portion.
