### ISSUE TITLE
[Provider]: GO Feature Flag Java

### ISSUE THREAD

**Issue by thomaspoignant** [open-feature/docs.openfeature.dev#151]
### SDK

Java

### Vendor/Tool

GO Feature Flag

### Maintainer

Community

### Artifacts

maven: https://mvnrepository.com/artifact/dev.openfeature.contrib.providers/go-feature-flag

### Repository

https://github.com/open-feature/java-sdk-contrib/tree/main/providers/go-feature-flag

### Anything else?

- Logo: https://github.com/thomaspoignant/go-feature-flag/raw/main/logo.png
- repository: https://github.com/thomaspoignant/go-feature-flag
- Website: https://gofeatureflag.org/
- Doc: https://docs.gofeatureflag.org/
- Twitter: @gofeatureflag

**Comment by toddbaert** [comment]
I think the maintainer here should be "community" since this is in the contribs!

I think we need to make it claerer in the template, but the `vendor` is meant to mean: is the provider in the OpenFeature org's source code, or a vendor's org/internal SCM.

**Comment by thomaspoignant** [comment]
>I think the maintainer here should be "community" since this is in the contribs!
I think we need to make it claerer in the template, but the vendor is meant to mean: is the provider in the OpenFeature org's source code, or a vendor's org/internal SCM.

I have changed it to community!
