### ISSUE TITLE
Getting Started with OpenFeature SDK

### ISSUE THREAD

**Issue by toddbaert** [open-feature/docs.openfeature.dev#21]
Add a [getting started](https://docs.openfeature.dev/docs/getting-started/overview) section for:

- installing the SDK (use multiple language to do npm, maven, nuget, etc)
- importing into a file
- setting a provider
- evaluating a boolean flag
- add links to flag evaluation doc and provider doc... consider linking to hooks?

**Comment by beeme1mr** [comment]
Hey @skyerus, would you mind looking into this? Focus on Go and we'll use what you come up with as a template for the other SDKs.

**Comment by skyerus** [comment]
@beeme1mr I've only just noticed this, I was on holiday when I was tagged and must've let the email slip by, apologies!

The go-sdk's readme has a decent getting started guide (in my humble opinion), what's the benefit to having a second getting started guide?

**Comment by beeme1mr** [comment]
Let's close this for now. We can reexamine post KubeCon to see if we need more information in the share docs.
