### ISSUE TITLE
Add golang code examples

### ISSUE THREAD

**Issue by toddbaert** [open-feature/docs.openfeature.dev#27]
We have TS/Java/C# code examples. We need golang as well.

Probably best to wait for the golang SDK to be somewhat complete: https://github.com/open-feature/golang-sdk.

**Comment by skyerus** [comment]
https://github.com/open-feature/docs.openfeature.dev/pull/31

**Comment by skyerus** [comment]
> @skyerus, can you also add a Go example [here](https://github.com/open-feature/docs.openfeature.dev/blob/main/docs/reference/concepts/02-provider.mdx) too?

Done: https://github.com/open-feature/docs.openfeature.dev/pull/68
