### ISSUE TITLE
[Provider]: LaunchDarkly OpenFeature provider for the Server-Side SDK for Java

### ISSUE THREAD

**Issue by kinyoklion** [open-feature/docs.openfeature.dev#278]
### SDK

Java

### Vendor/Tool

LaunchDarkly

### Maintainer

Vendor

### Artifacts

No artifact links.

### Repository

https://github.com/launchdarkly/openfeature-java-server

### Anything else?

Should have a logo from the dotnet and node provider.

**Comment by beeme1mr** [comment]
Thanks, I'll knock this out tomorrow.

**Comment by beeme1mr** [comment]
All good now, thanks @kinyoklion!

https://docs.openfeature.dev/docs/reference/technologies/server/java

**Comment by kinyoklion** [comment]
@beeme1mr Thank you!
