### ISSUE TITLE
[FEATURE] Add Algola search

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/docs.openfeature.dev#311]
### Requirements

Algola was gracious enough to provide us access to their search service. We need to add to Docusaurus and confirm that everything is configured correctly.

**Comment by Arhell** [comment]
i can add 
need 
```
 appId: 'app id',
 apiKey: '12345',
 indexName: 'name',
```

**Comment by beeme1mr** [comment]
This is a public id and key so it's safe to share in a GitHub comment.

```
appId: PH0VDWFP7Q
apiKey: 521034bef1ace79ba73f75d02324f83b
indexName: openfeature
```

Thanks @Arhell!
