### ISSUE TITLE
OpenSSF badging requirements

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/docs.openfeature.dev#6]
We have a few needs w/r/t openssf badging.

---

- [ ] The project website MUST provide information on how to: obtain, provide feedback (as bug reports or enhancements), and contribute to the software. [interact] 
- [ ]  The project MUST provide basic documentation for the software produced by the project. [documentation_basics] 
- [ ]  The project MUST provide reference documentation that describes the external interface (both input and output) of the software produced by the project. [documentation_interface] 
- [ ] The project MUST publish the process for reporting vulnerabilities on the project site. (URL required) [vulnerability_report_process] 
- [ ]  If private vulnerability reports are supported, the project MUST include how to send the information in a way that is kept private. (URL required) [vulnerability_report_private]

**Comment by beeme1mr** [comment]
I think org level issue templates may work.

**Comment by justinabrahms** [comment]
Alright. So to hit this requirement
> The project MUST provide reference documentation that describes the external interface (both input and output) of the software produced by the project. [documentation_interface]

I think I need to link to the javadoc. That's here: https://javadoc.io/doc/dev.openfeature/javasdk -- Any thoughts where I should link it?

**Comment by toddbaert** [comment]
> Alright. So to hit this requirement
> 
> > The project MUST provide reference documentation that describes the external interface (both input and output) of the software produced by the project. [documentation_interface]
> 
> I think I need to link to the javadoc. That's here: https://javadoc.io/doc/dev.openfeature/javasdk -- Any thoughts where I should link it?

I guess just in the README?

We could also structure our SDK readmes in a particular way and have them dynamically added to the docsite with @beeme1mr 's recent changes.

**Comment by beeme1mr** [comment]
I think this should be covered now in the docs and SDK READMEs
