### ISSUE TITLE
Add a .NET icon once it's added to Font Awesome

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/docs.openfeature.dev#61]
Add a .NET icon once it's added to Font Awesome

_Originally posted by @beeme1mr in https://github.com/open-feature/docs.openfeature.dev/pull/60#discussion_r943928313_

**Comment by toddbaert** [comment]
Ya, we could also make our own. Apparently there's no official C# logo? That might have something to do with it. I think there's a.NET one though.

**Comment by toddbaert** [comment]
Actually. I found older .NET and C# issues:

https://github.com/FortAwesome/Font-Awesome/issues/15505  and https://github.com/FortAwesome/Font-Awesome/issues/8365...

I think it's fair to say they wont appear any time soon. We can change this issue to use an SVG for this one.
