### ISSUE TITLE
language specific docs?

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/docs.openfeature.dev#7]
I have a big pile of javadoc. Should that live on the website?

openssf says I need:
1.  The project MUST provide basic documentation for the software produced by the project. [documentation_basics] 
1.  The project MUST provide reference documentation that describes the external interface (both input and output) of the software produced by the project. [documentation_interface]

For number 1, that seems like normal usage docs which we're already making.
For number 2.. that sounds like javadoc?

**Comment by beeme1mr** [comment]
I agree that number 1 should be covered by our docs. For number 2, I think the javadoc should be sufficient.
